### ISSUE TITLE
Submit package to Packagist

### ISSUE THREAD

**Issue by iggyvolz** [php/phd#59]
The repository contains a valid composer.json file, so the package could be installed via Composer, however attempting to `composer require php/phd` lists that the package could not be found.

Attempting to submit the package via https://packagist.org/packages/submit gives "The vendor name php is reserved, please use another name or reach out to us if you have a legitimate use for it."

**Comment by salathe** [comment]
See the discussion in https://github.com/php/phd/pull/39 for some context for the removal from Packagist.

Until PhD is actively maintained and in a releasable state for

**Comment by iggyvolz** [comment]
> See the discussion in https://github.com/php/phd/pull/39 for some context for the removal from Packagist.
> 

Apologies for the newbie question (and also if this isn't the right forum for this) - is there an effort anywhere to modernize/refactor the project at all?  It seems like the problem is the project isn't stable enough and I'd love to help with that, although I don't know how to start beyond just opening PRs for anything I find broken.

**Comment by kamil-tekiela** [comment]
That's a very good question. The project really needs a maintainer... but this is where the problem starts. This project needs tests to ensure we don't introduce regression issues. There's no point in adding tests for functionality that nobody uses, so we should identify who uses this project and which obsolete parts can be removed (e.g. PDF). Then we need someone to modernize the code and someone to review the changes. Currently, there are 2 PRs that are stuck in a limbo because of the points I just mentioned. We can verify that the happy path works for the use case that PHP.net has, but who will verify that the rest of the codebase still works?

Maybe this should be announced on the mailing list and if after some time nobody raises any objections, we internalize the project just for the purposes of php.net, add relevant tests and modernize the code base.
